# Site
name: "Ireland Magic Words"
title: "Ireland Magic Words"
description: "Happiness is important in our lives and it makes us feel better. We can celebrate happiness by inspiring others to spread love, positivity and encouraging them to do things they like. Together, we can make the world a better place."
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: 
google_analytics: 'G-E6Z4CMPQZR'
disqus: 
mailchimp-list: 
include: ["_pages"]
permalink: /:title/
shopenabled: false

collections:
  products:
    permalink: "/:collection/:name/"
    output: true
  posts:
    permalink: "/:collection/:year/:month/:day/:title/"
    output: true


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Snipcart
snipcartid: "OTc4MTliNjItOTM5ZS00NTQ3LTkzNmUtNWFlNzNiNDkwMDYyNjM4MTk2ODI2NzExMjc0Nzk4"

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-number"
adsense-data-ad-slot: "number"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
