url: https://www.irelandmagicwords.com/
baseurl: 

# Site settings
title: Ireland Magic Words
email: ireland.magicwords@gmail.com
description: "Happiness is important in our lives and it makes us feel better. We can celebrate happiness by inspiring others to spread love, positivity and encouraging them to do things they like. Together, we can make the world a better place. "


# Team names, titles and social links
people:

- name: Su
  pic: 2
  position: Magic Words Guru
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/IrelandWords1
  - title: facebook
    url: https://www.facebook.com/Irelandwordsshirley
  - title: instagram
    url: https://www.instagram.com/irelandmagicwords/

# Postal address (add as many lines as necessary)
address:
  - line: Planet Earth
  - line: 

# Build settings
markdown: kramdown
permalink: pretty